- Для выполнения задания потребуется самому сгенерировать данные с помощью модуля random (все пункты выполняются с помощью нее).

- Что необходимо, для создания будущей таблицы:

0) Для генерации данных в random необходимо установить seed = "АДВИ_2023", длина каждого списка N = 1000;

In [108]:
import pandas as pd
import random

random.seed("АДВИ_2023")

N = 1000

1) index колонка: создать список из N последовательных целых элементов от 1 до 1000 включительно, далее, с помощью специальной функции random перемешать его;

In [109]:
# Создаем список N последовательных целых элементов от 1 до 1000
index = list(range(1, N+1))

# Перемешиваем список с помощью функции shuffle
random.shuffle(index)

2) groups колонка: создать список из N элементов, состоящий из значений из списка ["группа_1", "группа_2", "группа_3", "группа_4", "группа_5"], необходимо использовать функцию из random которая возвращает список элементов длины k, выбранных из последовательности population с перестановкой элементов;

In [110]:
k = 1  # длина списка, который вернет функция sample
population = ["группа_1", "группа_2", "группа_3", "группа_4", "группа_5"]

# Создаем список groups с помощью функции sample
groups = random.choices(population, k=N)
# print(groups)

3) uniform колонка: создать список из N элементов, состоящий из целых значение из равномерного распределения [50, 100] ;

In [111]:
# Создаем список uniform из N целых значений, выбранных из равномерного распределения [50, 100]
uniform = [random.randint(50, 100) for i in range(N)]

# print(uniform)

4) gauss_1, gauss_2, gauss_3 колонки: Создать 3 списка из N элементов каждый, заполненные значениями из нормальных распределений с параметрами:
- μ = 0, σ**2 = 1 -> третья колонка gauss_1;
- μ = 0, σ**2 = 144 -> четвертая колонка gauss_2;
- μ = 50, σ**2 = 81 -> пятая колонка gauss_3;

In [112]:
# Создаем список gauss_1 из N элементов, выбранных из нормального распределения с параметрами μ = 0, σ^2 = 1
gauss_1 = [random.gauss(0, 1) for i in range(N)]

# Создаем список gauss_2 из N элементов, выбранных из нормального распределения с параметрами μ = 0, σ^2 = 144
gauss_2 = [random.gauss(0, 12) for i in range(N)]

# Создаем список gauss_3 из N элементов, выбранных из нормального распределения с параметрами μ = 50, σ^2 = 81
gauss_3 = [random.gauss(50, 9) for i in range(N)]

# print(gauss_1)
# print(gauss_2)
# print(gauss_3)

5) Создать pandas DataFrame, где (1) будет индексом, (2)-(4) колонки, названия колонок ["groups", "uniform", "gauss_1", "gauss_2", "gauss_3"] соответственно, не забывая проверить, что типы колонок должны соответствовать заявленным типам данных;

In [113]:
# Создаем DataFrame с помощью метода DataFrame библиотеки pandas
df = pd.DataFrame(
    {
        "groups": groups,
        "uniform": uniform,
        "gauss_1": gauss_1,
        "gauss_2": gauss_2,
        "gauss_3": gauss_3,
    },
    index=index,
)

print(df.dtypes)

df.head()

groups      object
uniform      int64
gauss_1    float64
gauss_2    float64
gauss_3    float64
dtype: object

       groups  uniform   gauss_1    gauss_2    gauss_3
476  группа_1       95  3.010291   2.156346  57.455851
315  группа_5       77  0.190277  -9.934550  62.694177
490  группа_4       96 -0.282161   9.211071  54.688895
748  группа_3       56  1.127080 -12.391793  30.192353
471  группа_5       52 -1.238270  10.938748  52.682052

6) Для колонок gauss_1 и gauss_2 заменить значения на None:

Для gauss_1, если индекс у значение делится на 121 без остатка;
Для gauss_2, если дробная часть больше 0.95;

In [114]:
# Заменяем значения в колонке gauss_1 на None для индексов, делящихся на 121 без остатка
df.loc[df.index % 121 == 0, "gauss_1"] = None

# Заменяем значения в колонке gauss_2 на None для значений, у которых дробная часть больше 0.95
df.loc[df["gauss_2"].apply(lambda x: x % 1 > 0.95), "gauss_2"] = None

# Выводим первые 5 строк DataFrame для проверки
df.head()

7) Теперь, для пропущенных значений gauss_1 и gauss_2:

Для gauss_2 None заменить на среднее по колонке;
Удалить строчки из таблицы, где gauss_1 == None.

In [116]:
# Заменяем пропущенные значения в колонке gauss_2 на среднее по колонке
df["gauss_2"].fillna(df["gauss_2"].mean(), inplace=True)

# Удаляем строки из таблицы, где gauss_1 == None
df.dropna(subset=["gauss_1"], inplace=True)

# Выводим первые 5 строк DataFrame для проверки
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 992 entries, 476 to 587
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   groups   992 non-null    object
 1   uniform  992 non-null    int64
 2   gauss_1  992 non-null    float64
 3   gauss_2  992 non-null    float64
 4   gauss_3  992 non-null    float64
dtypes: float64(3), int64(1), object(1)
memory usage: 46.5+ KB

In [ ]:
%%HTML
<h1>Первая строка из таблицы для сверки:</h1>
<p>|index|groups|uniform|gauss_1|gauss_2| gauss_3|</p>
<p>|476|группа_1|95|3.010291|2.156346|57.455853|</p>

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 992 entries, 476 to 587
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   groups   992 non-null    object
 1   uniform  992 non-null    int64
 2   gauss_1  992 non-null    float64
 3   gauss_2  992 non-null    float64
 4   gauss_3  992 non-null    float64
dtypes: float64(3), int64(1), object(1)
memory usage: 46.5+ KB

In [122]:
df.gauss_2.describe()

count    992.000000
mean      -0.257729
std       11.932412
min      -40.394911
25%       -8.027095
50%       -0.219773
75%        7.139698
max       34.218271
Name: gauss_2, dtype: float64

In [124]:
df.groups.value_counts()

группа_4    222
группа_1    215
группа_2    194
группа_3    184
группа_5    177
Name: groups, dtype: int64

In [127]:
df.groups[df.groups == 'группа_5'].index.min()

6

In [134]:
np.percentile (df.uniform , 90)

94.0

In [135]:
df.uniform[df.uniform >= 94].count()

118

In [151]:
df

       groups  uniform   gauss_1    gauss_2    gauss_3
476  группа_1       95  3.010291   2.156346  57.455851
315  группа_5       77  0.190277  -9.934550  62.694177
490  группа_4       96 -0.282161   9.211071  54.688895
748  группа_3       56  1.127080 -12.391793  30.192353
471  группа_5       52 -1.238270  10.938748  52.682052
..        ...      ...       ...        ...        ...
260  группа_4       57 -1.484164  -5.911598  49.330196
146  группа_4       78 -0.379041  -3.132954  60.329900
972  группа_1       52 -0.857206   0.835715  51.926114
161  группа_1       62 -0.195475   3.496498  66.310250
587  группа_5       60  0.093496  -9.164475  60.897843

[992 rows x 5 columns]

In [201]:
df.groupby(['groups'])['gauss_3'].median()

groups
группа_1    49.876708
группа_2    49.990529
группа_3    49.459261
группа_4    49.069511
группа_5    49.936910
Name: gauss_3, dtype: float64

In [213]:
df.groupby(['uniform']).min()

           groups   gauss_1    gauss_2    gauss_3     gauss
uniform
50       группа_1 -1.876449 -24.339342  37.925060 -0.365253
51       группа_1 -1.395004 -22.109394  26.145816 -0.770711
52       группа_1 -2.156552 -11.945886  32.696276 -0.262183
53       группа_1 -2.806862 -18.895489  30.058007 -0.346764
54       группа_1 -1.884175 -24.317209  30.828998 -0.379028
55       группа_1 -1.868984 -29.372732  35.179988 -0.535346
56       группа_1 -1.616146 -26.065953  30.192353 -0.542873
57       группа_1 -2.038693 -22.706587  29.324921 -0.427718
58       группа_1 -2.639733 -17.747276  29.828225 -0.356595
59       группа_1 -2.351985 -16.713825  34.053533 -0.508882
60       группа_1 -2.981714 -23.975737  33.617591 -0.480929
61       группа_1 -2.018770 -29.290553  30.152988 -0.606192
62       группа_1 -2.606773 -21.844500  30.378812 -0.671198
63       группа_1 -3.203481 -25.298616  33.660781 -0.538408
64       группа_1 -1.629511 -23.447372  30.728942 -0.428226
65       группа_1 -3.933254 -18.499952  36.572864 -0.386904
66       группа_1 -2.678406 -20.063586  43.640971 -0.399287
67       группа_1 -2.536981 -24.320282  20.268766 -0.511324
68       группа_1 -1.542551 -17.862768  21.111701 -0.308136
69       группа_1 -1.606673 -14.358516  27.741795 -0.277355
70       группа_1 -1.763494 -23.722245  19.682732 -0.642329
71       группа_1 -2.408125 -29.901064  37.419862 -0.841952
72       группа_1 -1.867466 -15.703960  24.617929 -0.307167
73       группа_1 -1.421189 -26.954793  33.716178 -0.694985
74       группа_1 -2.094399 -20.072490  29.872543 -0.481075
75       группа_1 -2.370745 -11.924087  36.149156 -0.254417
76       группа_1 -1.350069 -12.320735  34.083016 -0.279106
77       группа_1 -2.258939 -32.698466  31.089090 -0.708722
78       группа_1 -2.303046 -15.757225  29.411913 -0.284882
79       группа_1 -2.692705 -17.818580  28.793389 -0.414787
80       группа_1 -0.846966 -16.970803  38.988173 -0.405597
81       группа_1 -1.651022 -28.920612  36.811169 -0.520412
82       группа_1 -1.793932 -12.940111  37.615797 -0.321421
83       группа_1 -2.323960 -19.283499  34.331201 -0.409960
84       группа_1 -1.124005 -35.656081  26.901106 -1.029372
85       группа_1 -3.628448 -31.968739  40.272899 -0.761027
86       группа_2 -1.319226 -29.795362  39.003523 -0.677100
87       группа_1 -1.168087 -27.494794  34.144306 -0.574914
88       группа_1 -2.309203 -38.365537  33.929943 -0.608409
89       группа_1 -3.118084 -36.187520  31.377758 -0.784322
90       группа_1 -1.892301 -16.807327  29.945906 -0.358026
91       группа_1 -2.547899 -30.995174  33.534408 -0.600839
92       группа_1 -1.238202 -40.394911  33.037709 -0.779396
93       группа_1 -1.055858 -13.534119  33.923650 -0.368803
94       группа_1 -1.290248 -32.069324  34.010771 -0.656537
95       группа_1 -1.387249 -19.758698  40.440062 -0.426005
96       группа_1 -1.528546 -19.715359  33.424283 -0.402194
97       группа_1 -1.846776 -19.223256  36.882509 -0.428414
98       группа_1 -1.540623 -13.984643  36.748201 -0.330109
99       группа_1 -0.899213 -17.779739  28.673827 -0.409006
100      группа_1 -1.403259 -38.092289  26.063885 -0.843414

In [207]:
df['gauss'] = (df.gauss_1 + df.gauss_2) / df.gauss_3

In [208]:
df['gauss']

476    0.089924
315   -0.155425
490    0.163267
748   -0.373098
471    0.184133
         ...
260   -0.149924
146   -0.058213
972   -0.000414
161    0.049781
587   -0.148954
Name: gauss, Length: 992, dtype: float64

In [209]:
np.percentile (df.gauss , 70)

0.10641825158661447

In [ ]:
0.11